import { Prisma, PrismaClient } from "@prisma/client";
const prisma=new PrismaClient();
const rows:Array<[string,string,string,string]>=[
["menu.title","القائمة","Menu","Menu"],["menu.logout","تسجيل الخروج","Log out","Se déconnecter"],["menu.profile","الملف الشخصي","Profile","Profil"],["menu.wallet","المحفظة","Wallet","Portefeuille"],["menu.trips","الرحلات","Trips","Trajets"],["menu.places","الأماكن المحفوظة","Saved places","Lieux enregistrés"],["menu.notifications","الإشعارات","Notifications","Notifications"],["menu.coupons","الكوبونات","Coupons","Coupons"],["menu.referrals","الدعوات","Referrals","Parrainages"],["menu.subscriptions","الاشتراكات","Subscriptions","Abonnements"],["menu.support","المساعدة","Support","Assistance"],["menu.about","من نحن","About","À propos"],["menu.legal","المحتوى القانوني","Legal","Mentions légales"],["menu.settings","الإعدادات","Settings","Paramètres"],["menu.deleteAccount","حذف الحساب","Delete account","Supprimer le compte"],
["common.error","حدث خطأ. حاول مجددًا","Something went wrong","Une erreur est survenue"],["common.save","حفظ","Save","Enregistrer"],["common.cancel","إلغاء","Cancel","Annuler"],["common.delete","حذف","Delete","Supprimer"],["common.enabled","مفعّل","Enabled","Activé"],["common.disabled","غير مفعّل","Disabled","Désactivé"],["common.unavailable","المحتوى غير متاح حاليًا","Content is unavailable","Contenu indisponible"],
["trips.title","سجل الرحلات","Trip history","Historique des trajets"],["trips.details","تفاصيل الرحلة","Trip details","Détails du trajet"],["trips.empty","لا توجد رحلات","No trips yet","Aucun trajet"],["trips.destinationUnavailable","وجهة غير متاحة","Destination unavailable","Destination indisponible"],["trips.date","التاريخ","Date","Date"],["trips.driver","السائق","Driver","Chauffeur"],
["places.title","الأماكن المحفوظة","Saved places","Lieux enregistrés"],["places.add","إضافة مكان","Add place","Ajouter un lieu"],["places.label","اسم المكان","Place name","Nom du lieu"],["places.address","العنوان","Address","Adresse"],["places.empty","لا توجد أماكن محفوظة","No saved places","Aucun lieu enregistré"],["places.recents","الأماكن الحديثة","Recent places","Lieux récents"],["places.kind.HOME","المنزل","Home","Domicile"],["places.kind.WORK","العمل","Work","Travail"],["places.kind.OTHER","المفضلة","Favorite","Favori"],
["wallet.title","المحفظة","Wallet","Portefeuille"],["wallet.available","الرصيد المتاح","Available balance","Solde disponible"],["wallet.locked","الرصيد المحجوز","Locked balance","Solde bloqué"],["wallet.transactions","الحركات","Transactions","Transactions"],["wallet.empty","لا توجد حركات","No transactions","Aucune transaction"],
["notifications.title","الإشعارات","Notifications","Notifications"],["notifications.empty","لا توجد إشعارات","No notifications","Aucune notification"],["notifications.readAll","تعليم الكل كمقروء","Mark all read","Tout marquer comme lu"],["notifications.deleteAll","حذف الكل","Delete all","Tout supprimer"],["notifications.markRead","تعليم كمقروء","Mark read","Marquer comme lu"],["notifications.markUnread","تعليم كغير مقروء","Mark unread","Marquer comme non lu"],["notifications.unread","جديد","New","Nouveau"],["common.retry","إعادة المحاولة","Retry","Réessayer"],["coupons.title","الكوبونات","Coupons","Coupons"],["coupons.code","رمز الكوبون","Coupon code","Code promo"],["coupons.fare","قيمة الرحلة","Trip fare","Prix du trajet"],["coupons.validate","تحقق","Validate","Vérifier"],["coupons.discount","الخصم","Discount","Réduction"],["coupons.finalFare","السعر النهائي","Final fare","Prix final"],["coupons.invalid","الكوبون غير صالح","Invalid coupon","Coupon invalide"],
["referrals.title","الدعوات","Referrals","Parrainages"],["referrals.myCode","رمز دعوتي","My referral code","Mon code"],["referrals.share","مشاركة","Share","Partager"],["referrals.enterCode","أدخل رمز الدعوة","Enter referral code","Saisir le code"],["referrals.apply","تطبيق","Apply","Appliquer"],["referrals.history","السجل","History","Historique"],
["subscriptions.title","الاشتراكات","Subscriptions","Abonnements"],["subscriptions.status","الحالة","Status","Statut"],["subscriptions.renewal","التجديد التلقائي","Auto renewal","Renouvellement automatique"],["subscriptions.price","السعر","Price","Prix"],["subscriptions.subscribe","اشتراك","Subscribe","S’abonner"],["subscriptions.cancelRenewal","إلغاء التجديد","Cancel renewal","Annuler le renouvellement"],
["support.title","المساعدة","Support","Assistance"],["support.subject","الموضوع","Subject","Objet"],["support.message","الرسالة","Message","Message"],["support.send","إرسال","Send","Envoyer"],["support.myTickets","طلباتي","My tickets","Mes demandes"],["support.empty","لا توجد طلبات دعم","No support tickets","Aucune demande"],["support.details","تفاصيل الطلب","Ticket details","Détails de la demande"],["support.reply","الرد","Reply","Réponse"],
["profile.title","الملف الشخصي","Profile","Profil"],["profile.name","الاسم","Name","Nom"],["profile.phone","الهاتف","Phone","Téléphone"],["profile.email","البريد الإلكتروني","Email","E-mail"],["settings.title","الإعدادات","Settings","Paramètres"],["settings.language","اللغة","Language","Langue"],["language.ar","العربية","Arabic","Arabe"],["language.en","الإنجليزية","English","Anglais"],["language.fr","الفرنسية","French","Français"],["legal.title","المحتوى القانوني","Legal","Mentions légales"],["legal.version","الإصدار","Version","Version"],["legal.accept","أوافق على هذا الإصدار","Accept this version","Accepter cette version"],["legal.accepted","تمت الموافقة على هذا الإصدار","This version is accepted","Cette version est acceptée"],["about.title","من نحن","About","À propos"],
["accountDeletion.title","حذف الحساب","Delete account","Supprimer le compte"],["accountDeletion.warning","سيتم جدولة حذف الحساب ويمكنك التراجع خلال فترة السماح. تُحفظ السجلات المالية والقانونية المطلوبة وفق السياسة.","Deletion is scheduled after a grace period. Required financial and legal records are retained according to policy.","La suppression est planifiée après un délai de grâce. Les archives financières et légales requises sont conservées."],["accountDeletion.reason","السبب (اختياري)","Reason (optional)","Motif (facultatif)"],["accountDeletion.confirmation","اكتب عبارة التأكيد المعروضة","Type the confirmation phrase shown","Saisissez la phrase affichée"],["accountDeletion.submit","جدولة حذف الحساب","Schedule account deletion","Planifier la suppression"],["accountDeletion.pending","طلب الحذف قيد الانتظار","Deletion request pending","Demande en attente"],["accountDeletion.scheduledFor","موعد التنفيذ","Scheduled for","Prévue le"],["accountDeletion.cancel","إلغاء طلب الحذف","Cancel deletion request","Annuler la demande"],
["support.status.OPEN","مفتوح","Open","Ouvert"],["support.status.PENDING","قيد الانتظار","Pending","En attente"],["support.status.IN_PROGRESS","قيد المعالجة","In progress","En cours"],["support.status.RESOLVED","تم الحل","Resolved","Résolu"],["support.status.CLOSED","مغلق","Closed","Fermé"],
["referrals.status.PENDING","قيد الانتظار","Pending","En attente"],["referrals.status.COMPLETED","مكتمل","Completed","Terminé"],["referrals.status.REWARDED","تم منح المكافأة","Rewarded","Récompensé"],
["subscriptions.status.ACTIVE","نشط","Active","Actif"],["subscriptions.status.CANCELED","ملغى","Canceled","Annulé"],["subscriptions.status.EXPIRED","منتهي","Expired","Expiré"],
["trip.actions","إجراءات الرحلة","Trip actions","Actions du trajet"],["tripShare.title","تفاصيل رحلة flaminGO","flaminGO trip details","Détails du trajet flaminGO"],["tripShare.button","مشاركة تفاصيل الرحلة","Share trip details","Partager le trajet"],["tripShare.reference","مرجع الرحلة","Trip reference","Référence du trajet"],
["rating.title","قيّم رحلتك","Rate your trip","Évaluer le trajet"],["rating.stars","التقييم","Rating","Évaluation"],["rating.comment","تعليق اختياري","Optional comment","Commentaire facultatif"],["rating.submit","إرسال التقييم","Submit rating","Envoyer l’évaluation"],["rating.success","تم إرسال تقييمك","Rating submitted","Évaluation envoyée"],
["report.title","الإبلاغ عن الرحلة أو السائق","Report trip or driver","Signaler le trajet ou le chauffeur"],["report.message","اشرح ما حدث","Describe what happened","Décrivez ce qui s’est passé"],["report.submit","إرسال البلاغ","Submit report","Envoyer le signalement"],["report.success","تم إرسال البلاغ إلى فريق الدعم","Report sent to support","Signalement envoyé à l’assistance"],
["payment.title","الدفع","Payment","Paiement"],["payment.current","حالة الدفع","Payment status","État du paiement"],["payment.method","طريقة الدفع","Payment method","Mode de paiement"],["payment.status","الحالة","Status","Statut"],["payment.amount","المبلغ","Amount","Montant"],["payment.methods","طرق الدفع المتاحة","Available methods","Modes disponibles"],["payment.useMethod","استخدام طريقة الدفع","Use payment method","Utiliser ce mode"],["payment.none","لا توجد طريقة دفع متاحة حاليًا","No payment method is available","Aucun mode disponible"],["payment.method.CASH","نقدًا","Cash","Espèces"],["payment.method.WALLET","المحفظة","Wallet","Portefeuille"],["payment.method.CARD","البطاقة","Card","Carte"],["payment.status.PENDING","قيد الانتظار","Pending","En attente"],["payment.status.PROCESSING","قيد المعالجة","Processing","En cours"],["payment.status.PAID","مدفوع","Paid","Payé"],["payment.status.FAILED","فشل","Failed","Échoué"],["payment.status.REFUNDED","مسترد","Refunded","Remboursé"],["payment.status.CANCELED","ملغى","Canceled","Annulé"],
["communication.title","التواصل مع السائق","Contact driver","Contacter le chauffeur"],["communication.participant","طرف الرحلة","Trip participant","Participant au trajet"],["communication.active","التواصل متاح أثناء الرحلة","Communication is available during the trip","Communication disponible pendant le trajet"],["communication.inactive","انتهت صلاحية التواصل","Communication is no longer available","La communication n’est plus disponible"],["communication.call","اتصال آمن","Call securely","Appeler en sécurité"],["communication.empty","لا توجد رسائل","No messages","Aucun message"],["communication.message","اكتب رسالة","Write a message","Écrire un message"],["communication.send","إرسال","Send","Envoyer"],["communication.closed","الدردشة مغلقة","Chat closed","Discussion fermée"]];
const navigation={items:["Profile","Wallet","Trips","Places","Notifications","Coupons","Referrals","Subscriptions","Support","About","Legal","Settings","DeleteAccount"].map(route=>({route,labelKey:`menu.${route.charAt(0).toLowerCase()+route.slice(1)}`,enabled:true}))};
async function setting(key:string,value:Prisma.InputJsonValue){await prisma.setting.upsert({where:{key},create:{key,group:"passenger",value,publishedValue:value,isPublic:true,isSensitive:false,publicationStatus:"PUBLISHED",publishedVersion:1,publishedAt:new Date()},update:{value,publishedValue:value,isPublic:true,isSensitive:false,publicationStatus:"PUBLISHED",publishedVersion:{increment:1},publishedAt:new Date()}})}
async function main(){await setting("passenger.navigation",navigation);await setting("passenger.localization",{supportedLocales:["ar","fr","en"]});await setting("passenger.accountDeletion",{enabled:true,gracePeriodDays:30,confirmationText:"DELETE MY ACCOUNT"});await setting("passenger.paymentMethods",{methods:[{method:"CASH",enabled:true,labelKey:"payment.method.CASH"},{method:"WALLET",enabled:true,labelKey:"payment.method.WALLET"}]});await setting("passenger.tripCommunication",{enabled:true,chatEnabled:true,callEnabled:true,phoneMode:"DIRECT",activeStatuses:["ACCEPTED","ARRIVING","IN_PROGRESS"]});await setting("passenger.tripStatusNotifications",{ar:{ARRIVING:{title:"سائقك في الطريق",body:"السائق في طريقه إلى نقطة الانطلاق."},IN_PROGRESS:{title:"بدأت رحلتك",body:"انطلقت رحلتك الآن."},COMPLETED:{title:"اكتملت رحلتك",body:"وصلت إلى وجهتك."},CANCELLED:{title:"أُلغيت رحلتك",body:"تم إلغاء الرحلة."}},en:{ARRIVING:{title:"Your driver is on the way",body:"The driver is heading to the pickup point."},IN_PROGRESS:{title:"Your trip has started",body:"Your trip is now in progress."},COMPLETED:{title:"Trip completed",body:"You have reached your destination."},CANCELLED:{title:"Trip cancelled",body:"The trip was cancelled."}},fr:{ARRIVING:{title:"Votre chauffeur arrive",body:"Le chauffeur se dirige vers le point de départ."},IN_PROGRESS:{title:"Votre trajet a commencé",body:"Votre trajet est en cours."},COMPLETED:{title:"Trajet terminé",body:"Vous êtes arrivé à destination."},CANCELLED:{title:"Trajet annulé",body:"Le trajet a été annulé."}}});const maps={ar:{},en:{},fr:{}} as Record<string,Record<string,string>>;for(const [k,a,e,f] of rows){maps.ar[k]=a;maps.en[k]=e;maps.fr[k]=f}for(const locale of Object.keys(maps)){const old=await prisma.translationBundle.findUnique({where:{locale}});await prisma.translationBundle.upsert({where:{locale},create:{locale,messages:maps[locale],isActive:true},update:{messages:{...((old?.messages??{}) as object),...maps[locale]},isActive:true,version:{increment:1}}})}}
main().finally(()=>prisma.$disconnect());
