ALTER TABLE "VehicleType"
ADD COLUMN "appIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "clientOs" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "countryCodes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "audienceSegments" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "minAppVersion" TEXT,
ADD COLUMN "maxAppVersion" TEXT,
ADD COLUMN "badgeText" TEXT,
ADD COLUMN "etaMinutes" INTEGER;

ALTER TABLE "VehiclePricingRule"
ADD COLUMN "appIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "clientOs" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "audienceSegments" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "minAppVersion" TEXT,
ADD COLUMN "maxAppVersion" TEXT,
ADD COLUMN "metadata" JSONB;
